language: python
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=registry.iconicto.com/EveryThingFlutterBackend
before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - sudo chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - curl -LO $(curl -s https://api.github.com/repos/digitalocean/doctl/releases/latest | grep browser_download_url | grep linux-amd64 | cut -d '"' -f 4) | tar -xzv
  - sudo mv ~/doctl /usr/local/bin
  - doctl k8s cluster kubeconfig save $DIGITALOCEAN_CLUSTER -t DIGITALOCEAN_TOKEN
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: "Build the Container"
      script: docker build -f Deployment/Production/Dockerfile -t $IMAGE_NAME .
    - script: docker tag $IMAGE_NAME $IMAGE_NAME:commit-TRAVIS_COMMIT && docker tag $IMAGE_NAME $IMAGE_NAME:production
    - stage: "Pushing to Docker Registry"
      script: docker push $IMAGE_NAME
    - stage: "Deploying to the Cluster"
      deploy:
        provider: script
        script: kubectl set image deployment $DEPLOYMENT_NAME $IMAGE_NAME:commit-TRAVIS_COMMIT
        on:
          branch: master