dist: xenial
language: python
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=registry.iconicto.com/everything-flutter-backend
before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - sudo chmod +x ./kubectl
  - sudo chmod +x ./Deployment/Production/build.sh
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - sudo snap install doctl
  - sudo snap connect doctl:kube-config
  - doctl k8s cluster kubeconfig save $DIGITALOCEAN_CLUSTER -t $DIGITALOCEAN_TOKEN
  - echo $DOCKER_PASSWORD | docker login registry.iconicto.com -u $DOCKER_USERNAME --password-stdin

script:
  - docker build -f Deployment/Production/Dockerfile -t $IMAGE_NAME .
  - docker tag $IMAGE_NAME $IMAGE_NAME:commit-$TRAVIS_COMMIT
  - docker tag $IMAGE_NAME $IMAGE_NAME:production
  - docker push $IMAGE_NAME

deploy:
  provider: script
  script: kubectl set image deployment $DEPLOYMENT_NAME $IMAGE_NAME:commit-$TRAVIS_COMMIT
  on:
    branch: master