dist: xenial
sudo: required
services:
  - docker
env:
  global:
    - IMAGE_NAME=registry.iconicto.com/EveryThingFlutterBackend
before_install:
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - sudo chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - sudo snap install doctl
  - sudo snap connect doctl:kube-config
  - doctl k8s cluster kubeconfig save $DIGITALOCEAN_CLUSTER -t $DIGITALOCEAN_TOKEN
  - echo $DOCKER_PASSWORD | docker login registry.iconicto.com -u $DOCKER_USERNAME --password-stdin

jobs:
  include:
    - stage: "Build the Container"
      script: docker build -f Deployment/Production/Dockerfile -t $IMAGE_NAME .
    - script: docker tag $IMAGE_NAME $IMAGE_NAME:commit-TRAVIS_COMMIT && docker tag $IMAGE_NAME $IMAGE_NAME:production
    - stage: "Pushing to Docker Registry"
      script: docker push $IMAGE_NAME
    - stage: "Deploying to the Cluster"
      deploy:
        provider: script
        script: kubectl set image deployment $DEPLOYMENT_NAME $IMAGE_NAME:commit-TRAVIS_COMMIT
        on:
          branch: master