version: '3'

services:
  everythingflutter_db:
    image: postgres
    container_name: everythingflutter-Postgres-Development
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - postgres-everythingflutter:/var/lib/postgresql/data
  everythingflutter_web:
    container_name: everythingflutter-Django-Development
    build:
      context: ../..
      dockerfile: .github/development/Dockerfile
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SECRET: ${DJANGO_SECRET}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      PGPASSWORD: ${PGPASSWORD}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      S3_STORAGE_BUCKET_NAME: ${S3_STORAGE_BUCKET_NAME}
      AWS_DEFAULT_ACL: ${AWS_DEFAULT_ACL}
      CDN: ${CDN}
      PGUSER: ${PGUSER}
      PGHOST: ${PGHOST}
      PGNAME: ${PGNAME}
      PGPORT: ${PGPORT}
      DEBUG: ${DEBUG}
    volumes:
      - ../../:/app
    ports:
      - "8080:8000"
    depends_on:
      - everythingflutter_db
volumes:
  postgres-everythingflutter:
    driver: local