version: '3'

services:
  everythingflutter_db:
    image: postgres
    container_name: everythingflutter-Postgres-Development
    environment:
      POSTGRES_PASSWORD: ${PGPASSWORD}
    volumes:
      - postgres-everythingflutter:/var/lib/postgresql/data
  everythingflutter_web:
    container_name: everythingflutter-Django-Development
    build:
      context: ../../
      dockerfile: Deployment/Development/Dockerfile
    command: bash -c "python manage.py migrate --noinput && python manage.py runserver 0.0.0.0:8000"
    environment:
      PGPASSWORD: ${PGPASSWORD}
      DEBUG: ${DEBUG}
      S3_ACCESS_KEY_ID: ${S3_ACCESS_KEY_ID}
      S3_SECRET_ACCESS_KEY: ${S3_SECRET_ACCESS_KEY}
      S3_STORAGE_BUCKET_NAME: ${S3_STORAGE_BUCKET_NAME}
      STATIC_URL: ${STATIC_URL}
      AWS_DEFAULT_ACL: ${AWS_DEFAULT_ACL}
      S3_ENDPOINT_URL: ${S3_ENDPOINT_URL}
      CDN: ${CDN}
      PGNAME: ${PGNAME}
    volumes:
      - ../../:/app
    ports:
      - "8000:8000"
    depends_on:
      - everythingflutter_db
volumes:
  postgres-everythingflutter:
    driver: local